export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  agentmailApiKey: process.env.AGENTMAIL_API_KEY ?? "",
  agentmailSmithgroupKey: process.env.AGENTMAIL_SMITHGROUP_KEY ?? "",
  agentmailCaptivateKey: process.env.AGENTMAIL_CAPTIVATE_KEY ?? "",
  googleApiKey: process.env.GOOGLE_API_KEY ?? "",
  youtubeClientId: process.env.YOUTUBE_CLIENT_ID ?? "",
  youtubeClientSecret: process.env.YOUTUBE_CLIENT_SECRET ?? "",
  youtubeRedirectUri: process.env.OAUTH_REDIRECT_URI ?? "http://localhost:5000/api/auth/youtube/callback",
};
